version: '3.8'
services:
  access-key-service:
    image: access-key-service:latest
    build:
      context: ./access-key-service
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - '3000:3000'
    depends_on:
      - redis

  token-info-service:
    image: token-info-service:latest
    build:
      context: ./token-info-service
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - '3001:3001'
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
